- name: Garantir que o Docker está disponível
  ansible.builtin.command: docker info
  register: docker_status
  failed_when: docker_status.rc != 0
  changed_when: false

- name: Garantir diretório de dados do ligthrag
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user | default('kepler') }}"
    mode: '0755'
  loop: 
    - {path: '{{ ligthrag_data_dir }}'}

- name: Copiar stack e arquivos do ligthrag para o host remoto
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user | default('kepler') }}"
    mode: '0644'
  loop:
    - { src: 'service.yml', dest: '{{ ligthrag_stack_path }}' }
    - { src: '.env', dest: '{{ ligthrag_workdir }}/.env' }

- name: Garantir que o pip está instalado no host
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Garantir que o jsondiff está instalado (dependência do módulo docker_stack)
  ansible.builtin.pip:
    name: jsondiff
    state: present

- name: network app_network
  docker_network:
    name: app_network
    driver: overlay
    attachable: true
    state: present

- name: Implantar stack do ligthrag
  docker_stack:
    state: present
    name: ligthrag
    compose:
      - '{{ ligthrag_stack_path }}'