
machines = {
  "master" => {"memory" => "1024", "cpu" => "2", "ip" => "10", "image" => "ubuntu/jammy64"},
  "node01" => {"memory" => "1024", "cpu" => "2", "ip" => "11", "image" => "ubuntu/jammy64"},
  "node02" => {"memory" => "1024", "cpu" => "2", "ip" => "12", "image" => "ubuntu/jammy64"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.schenberk.example"
      machine.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/Docker-Lab"]
      end      
      machine.vm.provision "shell", path: "docker.sh"
      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
      machine.vm.provision "shell" do |s|
        ssh_prv_key = ""
        ssh_pub_key = ""
        if File.file?("./keys/id_rsa")
          # ssh_prv_key = File.read("./keys/id_rsa")
          ssh_pub_key = File.readlines("./keys/id_rsa.pub").first.strip
          name = "#{name}"
        else
          puts "No SSH key found. You will need to remedy this before pushing to the repository."
        end
        s.inline = <<-SHELL
          if grep -sq "#{ssh_pub_key}" /home/vagrant/.ssh/authorized_keys; then
            echo "SSH keys already provisioned."
            exit 0;
          fi
          echo "SSH key provisioning."
          mkdir -p /home/vagrant/.ssh/
          touch /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          exit 0
        SHELL
      end
      config.vm.provision "shell", inline: <<-EOF
        HOSTS=$(head -n7 /etc/hosts)
        echo -e "$HOSTS" > /etc/hosts
        echo '192.168.56.10 master.schenberk.example' >> /etc/hosts
        echo '192.168.56.11 node01.schenberk.example' >> /etc/hosts
        echo '192.168.56.12 node02.schenberk.example' >> /etc/hosts
        EOF
    end
  end
end