- name: Garantir que o Docker está disponível
  ansible.builtin.command: docker info
  register: docker_status
  failed_when: docker_status.rc != 0
  changed_when: false

- name: Garantir diretório de dados do Portainer
  ansible.builtin.file:
    path: "{{ portainer_data_dir }}"
    state: directory
    owner: "{{ ansible_user | default('kepler') }}"
    mode: '0755'

- name: Copiar stack do Portainer para o host remoto
  ansible.builtin.copy:
    src: service.yml
    dest: "{{ portainer_stack_path }}"
    owner: "{{ ansible_user | default('kepler') }}"
    mode: '0644'

- name: Garantir que o pip está instalado no host
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Garantir que o jsondiff está instalado (dependência do módulo docker_stack)
  ansible.builtin.pip:
    name: jsondiff
    state: present

- name: Implantar stack do Portainer
  docker_stack:
    state: present
    name: portainer
    compose:
      - '{{ portainer_stack_path }}'