# copiar o a stack do portainer "service.yml" para o host
- name: Implantar Portainer via Stack
  hosts: masters
  become: yes
  tasks:
    - name: Garantir diretório de dados do Portainer
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/portainer_data
        state: directory
        mode: '0755'

    - name: Garantir que o Docker esteja disponível
      command: docker info
      register: docker_status
      failed_when: docker_status.rc != 0
      changed_when: false

    - name: Copiar arquivo de stack do Portainer para o host remoto
      copy:
        src: ./service.yml
        dest: /home/{{ ansible_user }}/portainer_stack.yml
    
    - name: Implantar stack do Portainer no host remoto
      command: docker stack deploy -c /home/{{ ansible_user }}/portainer_stack.yml portainer

    - name: Exibir saída do deploy
      debug:
        var: deploy_result.stdout_linespl 